# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exhaust.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windowTyre(object):
        def setupUi(self, windowTyre):
                windowTyre.setObjectName("windowTyre")
                windowTyre.resize(1219, 801)
                self.centralwidget = QtWidgets.QWidget(windowTyre)
                self.centralwidget.setObjectName("centralwidget")
                self.frame = QtWidgets.QFrame(self.centralwidget)
                self.frame.setEnabled(True)
                self.frame.setGeometry(QtCore.QRect(-110, -20, 1741, 791))
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")

                #SLIP ON EXHAUST BUTTON
                self.sliponbutton = QtWidgets.QPushButton(self.frame)
                self.sliponbutton.setGeometry(QtCore.QRect(500, 280, 421, 71))
                self.sliponbutton.setStyleSheet("font: 15pt  \"ROG Fonts\";\n"
        "background-color: rgb(221, 221, 221);\n"
        "color: rgb(0,0,0);\n"
        "")
                self.sliponbutton.setObjectName("sliponbutton")


                #FULLSYSTEM EXHAUST BUTTON
                self.fullsysbutton = QtWidgets.QPushButton(self.frame)
                self.fullsysbutton.setGeometry(QtCore.QRect(500, 380, 421, 71))
                self.fullsysbutton.setStyleSheet("font: 15pt  \"ROG Fonts\";\n"
        "background-color: rgb(221, 221, 221);\n"
        "color: rgb(0,0,0);\n"
        "")
                self.fullsysbutton.setObjectName("fullsysbutton")



                self.back = QtWidgets.QPushButton(self.frame)
                self.back.setGeometry(QtCore.QRect(1110, 660, 111, 41))
                self.back.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap("../../../../Downloads/back-undo-return-button-png-5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.back.setIcon(icon)
                self.back.setObjectName("back")
                self.offroad = QtWidgets.QPushButton(self.frame)
                self.offroad.setEnabled(True)
                self.offroad.setGeometry(QtCore.QRect(1580, 370, 371, 71))
                font = QtGui.QFont()
                font.setFamily("ROG Fonts")
                font.setPointSize(13)
                font.setBold(False)
                font.setItalic(False)
                font.setUnderline(False)
                font.setWeight(50)
                font.setStrikeOut(False)
                self.offroad.setFont(font)
                self.offroad.setStyleSheet("font: 13pt  \"ROG Fonts\";\n"
        "background-color: rgb(221, 221, 221);\n"
        "color: rgb(0,0,0);\n"
        "")
                self.offroad.setObjectName("offroad")
                self.label_3 = QtWidgets.QLabel(self.frame)
                self.label_3.setEnabled(True)
                self.label_3.setGeometry(QtCore.QRect(1570, 410, 1581, 831))
                self.label_3.setText("")
                self.label_3.setPixmap(QtGui.QPixmap("../../OneDrive/Documents/GitHub/Compooter-Projekt/gui_testing_modified/torqucart.jpg"))
                self.label_3.setScaledContents(True)
                self.label_3.setObjectName("label_3")


                #FACTORY EXHAUST BUTTON
                self.factorybutton = QtWidgets.QLabel(self.frame)
                self.factorybutton.setGeometry(QtCore.QRect(-10, -20, 1541, 831))
                self.factorybutton.setText("")
                self.factorybutton.setPixmap(QtGui.QPixmap("torqucart.jpg"))
                self.factorybutton.setScaledContents(True)
                self.factorybutton.setObjectName("factorybutton")


                
                self.pushButton = QtWidgets.QPushButton(self.frame)
                self.pushButton.setGeometry(QtCore.QRect(500, 480, 421, 71))
                self.pushButton.setStyleSheet("font: 15pt  \"ROG Fonts\";\n"
        "background-color: rgb(221, 221, 221);\n"
        "color: rgb(0,0,0);")
                self.pushButton.setObjectName("pushButton")
                self.label_2 = QtWidgets.QLabel(self.frame)
                self.label_2.setGeometry(QtCore.QRect(450, 80, 511, 131))
                font = QtGui.QFont()
                font.setFamily("ROG Fonts")
                font.setPointSize(42)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.label_2.setFont(font)
                self.label_2.setStyleSheet("color: rgb(191, 191, 191);\n"
        "font: 42pt \"ROG Fonts\";")
                self.label_2.setObjectName("label_2")
                self.factorybutton.raise_()
                self.sliponbutton.raise_()
                self.fullsysbutton.raise_()
                self.back.raise_()
                self.offroad.raise_()
                self.label_3.raise_()
                self.pushButton.raise_()
                self.label_2.raise_()
                windowTyre.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(windowTyre)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 1219, 26))
                self.menubar.setObjectName("menubar")
                windowTyre.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(windowTyre)
                self.statusbar.setObjectName("statusbar")
                windowTyre.setStatusBar(self.statusbar)

                self.retranslateUi(windowTyre)
                QtCore.QMetaObject.connectSlotsByName(windowTyre)

                self.sliponbutton.clicked.connect(self.show_slipon)

        def retranslateUi(self, windowTyre):
                _translate = QtCore.QCoreApplication.translate
                windowTyre.setWindowTitle(_translate("windowTyre", "Tyre Window"))
                self.sliponbutton.setText(_translate("windowTyre", "SLIP ON EXHAUST"))
                self.fullsysbutton.setText(_translate("windowTyre", "FULL EXHAUST SYSTEM"))
                self.back.setText(_translate("windowTyre", "back"))
                self.offroad.setText(_translate("windowTyre", "CARBON UPGRADED STEERING"))
                self.pushButton.setText(_translate("windowTyre", "FACTORY EXHAUSTS"))
                self.label_2.setText(_translate("windowTyre", "EXHAUSTS"))
        
        def show_slipon(self, checked):
                self.w = 
                w.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    windowTyre = QtWidgets.QMainWindow()
    ui = Ui_windowTyre()
    ui.setupUi(windowTyre)
    windowTyre.show()
    sys.exit(app.exec_())
