# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import QMainWindow, QApplication, QLabel, QPushButton, QLineEdit, QDialog
from PyQt5 import QtWidgets
from PyQt5 import uic
from pathlib import Path

class Ui_offroadSuspensionWindow(QMainWindow):
    def __init__(self):
        super(Ui_offroadSuspensionWindow, self).__init__()

        filepath = Path(__file__).parent.resolve()
        filepath = Path.joinpath(filepath, 'offroad suspension.ui')
        # Load the ui file
        uic.loadUi(filepath,self)

        self.os1 = self.findChild(QPushButton, 'os1')
        self.os2 = self.findChild(QPushButton, 'os2')
        self.os3 = self.findChild(QPushButton, 'os3')

        self.os1.clicked.connect(self.os1_handler)
        self.os2.clicked.connect(self.os2_handler)
        self.os3.clicked.connect(self.os3_handler)



    def os1_handler(self):
        print("os1_handler")
        pass

    def os2_handler(self):
        print("os2_handler")
        pass

    def os3_handler(self):
        print("os3_handler")
        pass

class Ui_trackSuspensionWindow(QMainWindow):
    def __init__(self):
        super(Ui_trackSuspensionWindow, self).__init__()

        filepath = Path(__file__).parent.resolve()
        filepath = Path.joinpath(filepath, 'track suspension.ui')
        # Load the ui file
        uic.loadUi(filepath,self)

        self.ts1 = self.findChild(QPushButton, 'ts1')
        self.ts2 = self.findChild(QPushButton, 'ts2')
        self.ts3 = self.findChild(QPushButton, 'ts3')

        self.ts1.clicked.connect(self.ts1_handler)
        self.ts2.clicked.connect(self.ts2_handler)
        self.ts3.clicked.connect(self.ts3_handler)



    def ts1_handler(self):
        print("ts1_handler")
        pass

    def ts2_handler(self):
        print("ts2_handler")
        pass

    def ts3_handler(self):
        print("ts3_handler")
        pass


class Ui_airSuspensionWindow(QMainWindow):
    def __init__(self):
        super(Ui_airSuspensionWindow, self).__init__()

        filepath = Path(__file__).parent.resolve()
        filepath = Path.joinpath(filepath, 'air suspension.ui')
        # Load the ui file
        uic.loadUi(filepath,self)

        self.as1 = self.findChild(QPushButton, 'as1')
        self.as2 = self.findChild(QPushButton, 'as2')
        self.as3 = self.findChild(QPushButton, 'as3')

        self.as1.clicked.connect(self.as1_handler)
        self.as2.clicked.connect(self.as2_handler)
        self.as3.clicked.connect(self.as3_handler)



    def as1_handler(self):
        print("as1_handler")
        pass

    def as2_handler(self):
        print("as2_handler")
        pass

    def as3_handler(self):
        print("as3_handler")
        pass



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_offroadSuspensionWindow()
    ui.show()
    sys.exit(app.exec_())
