# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import QMainWindow, QApplication, QLabel, QPushButton, QLineEdit, QDialog
from PyQt5 import QtWidgets
from PyQt5 import uic
from pathlib import Path
from offroad_suspension import Ui_offroadSuspensionWindow
from offroad_suspension import Ui_trackSuspensionWindow
from offroad_suspension import Ui_airSuspensionWindow

class Ui_SuspensionWindow(QMainWindow):
    def __init__(self):
        super(Ui_SuspensionWindow, self).__init__()

        filepath = Path(__file__).parent.resolve()
        filepath = Path.joinpath(filepath, 'Suspension.ui')
        # Load the ui file
        uic.loadUi(filepath,self)

        self.air = self.findChild(QPushButton, 'air')
        self.track = self.findChild(QPushButton, 'track')
        self.offroad = self.findChild(QPushButton, 'offroad')

        self.air.clicked.connect(self.air_handler)
        self.track.clicked.connect(self.track_handler)
        self.offroad.clicked.connect(self.offroad_handler)



    def air_handler(self):
        print("air_handler")
        self.air_suspension = Ui_airSuspensionWindow()
        self.air_suspension.show()
        pass

    def track_handler(self):
        print("track_handler")
        self.track_suspension = Ui_trackSuspensionWindow()
        self.track_suspension.show()
        pass

    def offroad_handler(self):
        print("offroad_handler")
        self.offroad_suspension = Ui_offroadSuspensionWindow()
        self.offroad_suspension.show()
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_SuspensionWindow()
    ui.show()
    sys.exit(app.exec_())
