# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'website_proj2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window1(object):
    def setupUi(self, window1):
        window1.setObjectName("window1")
        window1.resize(700, 500)
        self.centralwidget = QtWidgets.QWidget(window1)
        self.centralwidget.setObjectName("centralwidget")
        self.main_header_name = QtWidgets.QLabel(self.centralwidget)
        self.main_header_name.setGeometry(QtCore.QRect(120, 10, 331, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.main_header_name.setFont(font)
        self.main_header_name.setObjectName("main_header_name")
        self.tyreButton = QtWidgets.QPushButton(self.centralwidget)
        self.tyreButton.setGeometry(QtCore.QRect(120, 80, 56, 20))
        self.tyreButton.setObjectName("tyreButton")
        self.steeringButton = QtWidgets.QPushButton(self.centralwidget)
        self.steeringButton.setGeometry(QtCore.QRect(210, 80, 56, 20))
        self.steeringButton.setObjectName("steeringButton")
        self.engineButton = QtWidgets.QPushButton(self.centralwidget)
        self.engineButton.setGeometry(QtCore.QRect(290, 80, 56, 21))
        self.engineButton.setObjectName("engineButton")
        self.suspensionButton = QtWidgets.QPushButton(self.centralwidget)
        self.suspensionButton.setGeometry(QtCore.QRect(380, 80, 56, 21))
        self.suspensionButton.setObjectName("suspensionButton")
        self.emailLabel = QtWidgets.QLabel(self.centralwidget)
        self.emailLabel.setGeometry(QtCore.QRect(130, 280, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.emailLabel.setFont(font)
        self.emailLabel.setObjectName("emailLabel")
        self.contactLabel = QtWidgets.QLabel(self.centralwidget)
        self.contactLabel.setGeometry(QtCore.QRect(130, 250, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.contactLabel.setFont(font)
        self.contactLabel.setObjectName("contactLabel")
        self.phone_label = QtWidgets.QLabel(self.centralwidget)
        self.phone_label.setGeometry(QtCore.QRect(130, 320, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.phone_label.setFont(font)
        self.phone_label.setObjectName("phone_label")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(750, 0, 16, 581))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        window1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 18))
        self.menubar.setObjectName("menubar")
        window1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(window1)
        self.statusbar.setObjectName("statusbar")
        window1.setStatusBar(self.statusbar)

        self.retranslateUi(window1)
        QtCore.QMetaObject.connectSlotsByName(window1)

    def retranslateUi(self, window1):
        _translate = QtCore.QCoreApplication.translate
        window1.setWindowTitle(_translate("window1", "MainWindow"))
        self.main_header_name.setText(_translate("window1", "flipkart(placeholder)"))
        self.tyreButton.setText(_translate("window1", "Tyres"))
        self.steeringButton.setText(_translate("window1", "Steering"))
        self.engineButton.setText(_translate("window1", "Engine Parts"))
        self.suspensionButton.setText(_translate("window1", "Suspension"))
        self.emailLabel.setText(_translate("window1", "Email: "))
        self.contactLabel.setText(_translate("window1", "Contact us:"))
        self.phone_label.setText(_translate("window1", "Phone:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window1 = QtWidgets.QMainWindow()
    ui = Ui_window1()
    ui.setupUi(window1)
    window1.show()
    sys.exit(app.exec_())
